; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32 @6.5.0
board = esp32s3_flash_16MB
framework = arduino
monitor_speed = 115200 ;Serial Baud Rate Setting

; debug_tool = esp-builtin
; upload_protocol = esp-builtin
upload_speed = 921600 ; 460800, 512000, 460800, 256000, 115200
board_upload.flash_size = 16MB 

board_build.memory_type = qio_opi ;Enable internal PSRAM
; board_build.memory_type = qio_qspi ;Enable external PSRAM

board_build.partitions = default_16MB.csv 

build_flags = 
    -Wall ;all errors that everybody could agree on
    -Wextra ;somebody agree on
    ; -Werror ;Think of "Warning" as "Error".
    -D CORE_DEBUG_LEVEL=1 ;Debug level 0-5
    ; -D BOARD_HAS_PSRAM ;Enable external PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ;1 is to use the USB port as a serial port
    -D ARDUINO_RUNNING_CORE=1       ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1 ; Events Run On Core

[platformio]
boards_dir = ./boards
lib_dir = ./libraries

src_dir = examples/${platformio.default_envs}
; default_envs = GFX
; default_envs = CHSC5816
; default_envs = Rotary_Encoder
default_envs = Lvgl_CIT
; default_envs = UI_demo              ;This runs only in the `PlatformIO` environment

; src_dir = debug/examples/${platformio.default_envs}
; default_envs = AMOLED_Test
; default_envs = Chip_Scan
; default_envs = DO0143FAT01
; default_envs = FT3268
; default_envs = GFX_FT3268_Image
; default_envs = GFX_Image
; default_envs = GFX_PDQ
; default_envs = IIC_Scan_2
; default_envs = IO
; default_envs = Lvgl_benchmark
; default_envs = Rotary_Encoder_WS2812B
; default_envs = WS2812B_Blink
; default_envs = WS2812B_ColorPalette

[env:GFX]
[env:CHSC5816]
[env:Rotary_Encoder]
[env:Lvgl_CIT]
build_flags = 
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_USE_DCLOCK ;Using lvgl DCLOCK components
    -D LV_USE_CAROUSEL

[env:UI_demo]

[env:IO]
[env:GFX_Image]
[env:GFX_PDQ]
[env:DO0143FAT01]
[env:AMOLED_Test]
[env:FT3268]
[env:GFX_FT3268_Image]
[env:Chip_Scan]
[env:WS2812B_ColorPalette]
[env:WS2812B_Blink]
[env:Lvgl_benchmark]
[env:IIC_Scan_2]
[env:Rotary_Encoder_WS2812B]

